version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: stg_payments
    meta:
        owner: "@drew"
        contains_pii: true
        SLA: "1 hour"
    columns:
      - name: payment_id
        tags: ['billing']
        tests:
          - unique
          - not_null
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

  - name: hidden_model
    docs:
      show: false

sources:
    # Hack: use a seed
    - name: payments
      schema: "{{ target.schema }}"
      tables:
        - name: orders
          identifier: "raw_orders"
        - name: tagged_source
          identifier: "raw_customers"
          tags: ['important']
