changesDir: .changes
unreleasedDir: unreleased
kinds:
- label: Docs
custom:
- key: Author
  label: GitHub Username(s) (separated by a single space if multiple)
  type: string
  minLength: 3
- key: Issue
  label: GitHub Issue Number
  type: string
  minLength: 2
- key: PR
  label: GitHub Pull Request Number
  type: string
  minLength: 2

