name: 🛠️ Implementation
description: This is an implementation ticket intended for use by the maintainers of dbt-oss-template
title: "[<project>] <title>"
labels: ["user docs"]
body:
  - type: markdown
    attributes:
      value: This is an implementation ticket intended for use by the maintainers of dbt-oss-template
  - type: checkboxes
    attributes:
      label: Housekeeping
      description: >
        A couple friendly reminders:
          1. Remove the `user docs` label if the scope of this work does not require changes to https://docs.getdbt.com/docs: no end-user interface (e.g. yml spec, CLI, error messages, etc) or functional changes
          2. Link any blocking issues in the "Blocked on" field under the "Core devs & maintainers" project.
      options:
        - label: I am a maintainer of dbt-oss-template
          required: true
  - type: textarea
    attributes:
      label: Short description
      description: |
        Describe the scope of the ticket, a high-level implementation approach and any tradeoffs to consider
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance criteria
      description: |
        What is the definition of done for this ticket? Include any relevant edge cases and/or test cases
    validations:
      required: true
  - type: textarea
    attributes:
      label: Impact to Other Teams
      description: |
        Will this change impact other teams?  Include details of the kinds of changes required (new tests, code changes, related tickets) and _add the relevant `Impact:[team]` label_.
      placeholder: |
        Example: This change impacts `dbt-redshift` because the tests will need to be modified.  The `Impact:[Adapter]` label has been added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Will backports be required?
      description: |
        Will this change need to be backported to previous versions?  Add details, possible blockers to backporting and _add the relevant backport labels `backport 1.x.latest`_
      placeholder: |
        Example: Backport to 1.6.latest, 1.5.latest and 1.4.latest.  Since 1.4 isn't using click, the backport may be complicated. The `backport 1.6.latest`, `backport 1.5.latest` and `backport 1.4.latest` labels have been added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: |
        Provide the "why", motivation, and alternative approaches considered -- linking to previous refinement issues, spikes, docs as appropriate
          validations:
    validations:
      required: false
